# Generated by Django 3.2 on 2021-10-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submessage',
            name='room',
            field=models.CharField(max_length=100),
        ),
    ]
