# Generated by Django 3.2 on 2021-09-12 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_rename_chats_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='specific_room_chat',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
