# Generated by Django 3.2 on 2021-10-19 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_submessage_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submessage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.room'),
        ),
    ]
