# Generated by Django 3.2 on 2021-09-12 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_auto_20210912_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_chat', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='specific_room_chat',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='chats.chat'),
        ),
    ]
